"""
plots.py — Generate thesis-quality figures.

Reads metrics from results/eval_metrics.pkl (generated by eval_all.py)
Generates figures in results/figures/

Figures:
    1. node_comparison.png    — AUC/F1 bar chart for all nodes
    2. confusion_nodeA.png    — Confusion matrix for Node A
    3. confusion_nodeB.png    — Confusion matrix for Node B
    4. confusion_nodeC.png    — Confusion matrix for Node C
    5. fusion_improvement.png — Audio-only vs Fusion comparison
    6. roc_curves.png         — ROC curves for binary nodes (A, B)
    7. system_overview.png    — Full pipeline results summary

Usage:
    python src/evaluation/plots.py

Requires: matplotlib, seaborn (pip install matplotlib seaborn)
"""

import pickle
import sys
from pathlib import Path

import numpy as np

_THIS_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _THIS_DIR.parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

def _p(relative_path: str) -> str:
    """Resolve path relative to project root."""
    return str(_PROJECT_ROOT / relative_path)

try:
    import matplotlib
    matplotlib.use("Agg")  # Non-interactive backend (works without display)
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    HAS_MPL = True
except ImportError:
    HAS_MPL = False
    print("  ⚠️  matplotlib not installed. Run: pip install matplotlib")

try:
    import seaborn as sns
    HAS_SNS = True
except ImportError:
    HAS_SNS = False


def setup_style():
    """Set publication-quality defaults."""
    if not HAS_MPL:
        return
    plt.rcParams.update({
        "figure.figsize": (8, 5),
        "figure.dpi": 150,
        "font.size": 12,
        "axes.titlesize": 14,
        "axes.labelsize": 12,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "legend.fontsize": 10,
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "axes.grid": True,
        "grid.alpha": 0.3,
    })
    if HAS_SNS:
        sns.set_palette("Set2")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 1: Node comparison bar chart
# ═══════════════════════════════════════════════════════════════════════════════

def plot_node_comparison(metrics: dict, save_dir: Path):
    """Bar chart comparing all nodes."""
    if not HAS_MPL:
        return

    nodes = []
    values = []
    metric_names = []

    if "node_a" in metrics:
        nodes.append("Node A\n(hungry)")
        values.append(metrics["node_a"]["auc"])
        metric_names.append("AUC")

    if "node_b" in metrics:
        nodes.append("Node B\n(tired)")
        values.append(metrics["node_b"]["auc"])
        metric_names.append("AUC")

    if "node_c" in metrics:
        nodes.append("Node C\n(discomfort)")
        values.append(metrics["node_c"]["f1_macro"])
        metric_names.append("F1")

    if not nodes:
        return

    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ["#5470C6", "#91CC75", "#FAC858"]
    bars = ax.bar(nodes, values, color=colors[:len(nodes)], width=0.5, edgecolor="white")

    # Add value labels on bars
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.02,
                f"{val:.3f}", ha="center", va="bottom", fontweight="bold", fontsize=13)

    ax.set_ylabel("Score (AUC / F1)")
    ax.set_title("Audio-Only Performance per Node")
    ax.set_ylim(0, 1.1)
    ax.axhline(y=0.5, color="red", linestyle="--", alpha=0.5, label="Random baseline")
    ax.legend()

    plt.tight_layout()
    path = save_dir / "node_comparison.png"
    plt.savefig(path, bbox_inches="tight")
    plt.close()
    print(f"  ✅ {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 2-4: Confusion matrices
# ═══════════════════════════════════════════════════════════════════════════════

def plot_confusion(cm, classes, title, save_path):
    """Plot a confusion matrix."""
    if not HAS_MPL:
        return

    fig, ax = plt.subplots(figsize=(6, 5))
    cm_array = np.array(cm)

    if HAS_SNS:
        sns.heatmap(cm_array, annot=True, fmt="d", cmap="Blues",
                    xticklabels=classes, yticklabels=classes, ax=ax,
                    cbar_kws={"shrink": 0.8})
    else:
        im = ax.imshow(cm_array, cmap="Blues")
        for i in range(len(classes)):
            for j in range(len(classes)):
                ax.text(j, i, str(cm_array[i, j]),
                        ha="center", va="center", fontsize=14,
                        color="white" if cm_array[i, j] > cm_array.max() / 2 else "black")
        ax.set_xticks(range(len(classes)))
        ax.set_yticks(range(len(classes)))
        ax.set_xticklabels(classes)
        ax.set_yticklabels(classes)
        plt.colorbar(im, ax=ax, shrink=0.8)

    ax.set_xlabel("Predicted")
    ax.set_ylabel("True")
    ax.set_title(title)

    plt.tight_layout()
    plt.savefig(save_path, bbox_inches="tight")
    plt.close()
    print(f"  ✅ {save_path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 5: Fusion improvement
# ═══════════════════════════════════════════════════════════════════════════════

def plot_fusion_improvement(metrics: dict, save_dir: Path):
    """Bar chart: audio vs audio+bio vs audio+bio+video."""
    if not HAS_MPL or "fusion" not in metrics:
        return

    fm = metrics["fusion"]

    fig, ax = plt.subplots(figsize=(9, 5.5))

    categories = ["Accuracy", "F1 (hungry)"]

    audio_vals = [fm["acc_audio_only"], fm["f1_audio_only"]]
    ab_vals = [fm["acc_audio_bio"], fm["f1_audio_bio"]]
    abv_vals = [fm["acc_audio_bio_video"], fm["f1_audio_bio_video"]]

    x = np.arange(len(categories))
    width = 0.22

    bars1 = ax.bar(x - width, audio_vals, width, label="Audio only",
                   color="#EE6666", edgecolor="white")
    bars2 = ax.bar(x, ab_vals, width, label="Audio + Bio",
                   color="#5470C6", edgecolor="white")
    bars3 = ax.bar(x + width, abv_vals, width, label="Audio + Bio + Video",
                   color="#91CC75", edgecolor="white")

    for bars in [bars1, bars2, bars3]:
        for bar in bars:
            h = bar.get_height()
            ax.text(bar.get_x() + bar.get_width() / 2, h + 0.015,
                    f"{h:.3f}", ha="center", va="bottom", fontsize=10)

    ax.set_ylabel("Score")
    ax.set_title("Multimodal Fusion: Audio vs Audio+Bio vs Audio+Bio+Video")
    ax.set_xticks(x)
    ax.set_xticklabels(categories)
    ax.set_ylim(0, 1.12)
    ax.legend()
    ax.axhline(y=0.5, color="gray", linestyle="--", alpha=0.4)

    # Improvement annotations
    imp_total = fm["improvement_total"]
    ax.annotate(f"Total: {imp_total:+.1%} improvement",
                xy=(0.5, 0.96), xycoords="axes fraction",
                fontsize=13, fontweight="bold", color="green",
                ha="center",
                bbox=dict(boxstyle="round,pad=0.3", facecolor="lightyellow", alpha=0.8))

    plt.tight_layout()
    path = save_dir / "fusion_improvement.png"
    plt.savefig(path, bbox_inches="tight")
    plt.close()
    print(f"  ✅ {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 6: ROC Curves for binary nodes
# ═══════════════════════════════════════════════════════════════════════════════

def plot_roc_curves(metrics: dict, save_dir: Path):
    """ROC curves for Node A and Node B."""
    if not HAS_MPL:
        return

    from sklearn.metrics import roc_curve

    fig, ax = plt.subplots(figsize=(7, 6))

    colors = {"node_a": "#5470C6", "node_b": "#91CC75"}
    labels = {"node_a": "Node A (hungry)", "node_b": "Node B (tired)"}

    for node_key in ["node_a", "node_b"]:
        if node_key not in metrics:
            continue
        m = metrics[node_key]
        if "y_test" not in m or "p_test" not in m:
            continue

        y = np.array(m["y_test"])
        p = np.array(m["p_test"])
        fpr, tpr, _ = roc_curve(y, p)
        auc = m["auc"]

        ax.plot(fpr, tpr, color=colors[node_key], linewidth=2,
                label=f"{labels[node_key]} (AUC={auc:.3f})")

    ax.plot([0, 1], [0, 1], "k--", alpha=0.4, label="Random")
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title("ROC Curves — Audio-Only Binary Nodes")
    ax.legend(loc="lower right")
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)

    plt.tight_layout()
    path = save_dir / "roc_curves.png"
    plt.savefig(path, bbox_inches="tight")
    plt.close()
    print(f"  ✅ {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 7: System overview
# ═══════════════════════════════════════════════════════════════════════════════

def plot_system_overview(metrics: dict, save_dir: Path):
    """Summary figure showing the full pipeline results."""
    if not HAS_MPL:
        return

    fig, axes = plt.subplots(1, 3, figsize=(14, 5))

    # Panel 1: Node performance
    ax = axes[0]
    nodes_data = []
    if "node_a" in metrics:
        nodes_data.append(("Node A\nhungry", metrics["node_a"]["auc"], "#5470C6"))
    if "node_b" in metrics:
        nodes_data.append(("Node B\ntired", metrics["node_b"]["auc"], "#91CC75"))
    if "node_c" in metrics:
        nodes_data.append(("Node C\ndiscomfort", metrics["node_c"]["f1_macro"], "#FAC858"))

    if nodes_data:
        names, vals, cols = zip(*nodes_data)
        bars = ax.bar(names, vals, color=cols, edgecolor="white")
        for b, v in zip(bars, vals):
            ax.text(b.get_x() + b.get_width() / 2, v + 0.02, f"{v:.3f}",
                    ha="center", fontsize=10, fontweight="bold")
    ax.set_title("Audio-Only Nodes")
    ax.set_ylim(0, 1.1)
    ax.axhline(0.5, color="red", ls="--", alpha=0.4)

    # Panel 2: Fusion comparison
    ax = axes[1]
    if "fusion" in metrics:
        fm = metrics["fusion"]
        cats = ["Audio\nonly", "Audio\n+ Bio", "A+B\n+Video"]
        vals = [fm["acc_audio_only"], fm["acc_audio_bio"], fm["acc_audio_bio_video"]]
        cols = ["#EE6666", "#5470C6", "#91CC75"]
        bars = ax.bar(cats, vals, color=cols, edgecolor="white", width=0.5)
        for b, v in zip(bars, vals):
            ax.text(b.get_x() + b.get_width() / 2, v + 0.02, f"{v:.3f}",
                    ha="center", fontsize=10, fontweight="bold")
        imp = fm["improvement_total"]
        ax.set_title(f"Fusion ({'+' if imp>0 else ''}{imp:.1%})")
    else:
        ax.set_title("Fusion (no data)")
    ax.set_ylim(0, 1.1)

    # Panel 3: Modality contribution text
    ax = axes[2]
    ax.axis("off")
    text_lines = [
        "System Summary",
        "─" * 30,
        "",
    ]
    if "node_a" in metrics:
        text_lines.append(f"Node A AUC: {metrics['node_a']['auc']:.3f}")
    if "node_b" in metrics:
        text_lines.append(f"Node B AUC: {metrics['node_b']['auc']:.3f}")
    if "node_c" in metrics:
        text_lines.append(f"Node C F1:  {metrics['node_c']['f1_macro']:.3f}")
    if "fusion" in metrics:
        text_lines.append("")
        text_lines.append(f"Audio only: {metrics['fusion']['acc_audio_only']:.3f}")
        text_lines.append(f"+Bio:       {metrics['fusion']['acc_audio_bio']:.3f}")
        text_lines.append(f"+Bio+Video: {metrics['fusion']['acc_audio_bio_video']:.3f}")
        text_lines.append(f"Total gain: {metrics['fusion']['improvement_total']:+.1%}")
    text_lines.append("")
    text_lines.append("Key finding:")
    text_lines.append("Bio context rescues")
    text_lines.append("weak audio signals")

    ax.text(0.1, 0.95, "\n".join(text_lines), transform=ax.transAxes,
            fontsize=11, verticalalignment="top", fontfamily="monospace",
            bbox=dict(boxstyle="round", facecolor="lightyellow", alpha=0.8))
    ax.set_title("Overview")

    plt.suptitle("InfantCryNet — Full Pipeline Evaluation", fontsize=15, fontweight="bold")
    plt.tight_layout()
    path = save_dir / "system_overview.png"
    plt.savefig(path, bbox_inches="tight")
    plt.close()
    print(f"  ✅ {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    print("=" * 60)
    print("  Generating thesis figures")
    print("=" * 60)

    if not HAS_MPL:
        print("\n  ❌ matplotlib not installed")
        print("  Run: pip install matplotlib seaborn")
        return

    setup_style()

    # Load metrics
    metrics_path = Path(_p("results/eval_metrics.pkl"))
    if not metrics_path.exists():
        print(f"\n  ❌ Metrics not found: {metrics_path}")
        print("  Run eval_all.py first!")
        return

    with open(metrics_path, "rb") as f:
        metrics = pickle.load(f)

    print(f"  Loaded metrics: {list(metrics.keys())}")

    save_dir = Path(_p("results/figures"))
    save_dir.mkdir(parents=True, exist_ok=True)

    # Generate all figures
    print(f"\n  Generating figures in {save_dir}/\n")

    plot_node_comparison(metrics, save_dir)

    if "node_a" in metrics and "confusion_matrix" in metrics["node_a"]:
        plot_confusion(
            metrics["node_a"]["confusion_matrix"],
            ["non_hungry", "hungry"],
            "Node A: Hungry vs Non-Hungry",
            save_dir / "confusion_nodeA.png",
        )

    if "node_b" in metrics and "confusion_matrix" in metrics["node_b"]:
        plot_confusion(
            metrics["node_b"]["confusion_matrix"],
            ["active", "tired"],
            "Node B: Tired vs Active",
            save_dir / "confusion_nodeB.png",
        )

    if "node_c" in metrics and "confusion_matrix" in metrics["node_c"]:
        plot_confusion(
            metrics["node_c"]["confusion_matrix"],
            metrics["node_c"]["classes"],
            "Node C: Discomfort Sub-types",
            save_dir / "confusion_nodeC.png",
        )

    plot_fusion_improvement(metrics, save_dir)
    plot_roc_curves(metrics, save_dir)
    plot_system_overview(metrics, save_dir)

    print(f"\n  All figures saved to: {save_dir}/")
    print("  Done ✅")


if __name__ == "__main__":
    main()